name: onmarcy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  splashscreen: 
  google_fonts: ^2.3.1
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  firebase_auth: ^3.3.9
  google_sign_in: ^5.2.4

  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_native_splash: ^2.0.1+1
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  background_image: assets/splash.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/